name: slashping

services:
  web:
    build:
      context: .
      dockerfile: ./dockerfiles/web.dockerfile
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - ./env/web.env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  db:
    image: postgres:16
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - ./env/db.env

  redis:
    image: redis:7.2
    volumes:
      - ./data/redis:/data
  
  celery:
    build:
      context: .
      dockerfile: ./dockerfiles/web.dockerfile
    command: celery -A core worker --loglevel=info -B
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - ./env/web.env
    depends_on:
      - db
      - redis
  
  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - "8025:8025"
  
  node:
    build:
      context: .
      dockerfile: ./dockerfiles/node.dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - web
