# Generated by Django 5.1.4 on 2025-03-28 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="last_pinged_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
