# Generated by Django 5.1.4 on 2025-03-26 08:10

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_new_client_in_days_user_new_client_target_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(
                blank=True, null=True, upload_to=accounts.models.user_directory_path
            ),
        ),
    ]
