# Generated by Django 5.1.4 on 2025-04-01 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_last_mail_sent_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="last_mail_sent_at",
            new_name="last_customers_mail_sent_at",
        ),
    ]
