# Generated by Django 5.1.4 on 2025-04-01 10:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_rename_last_mail_sent_at_user_last_customers_mail_sent_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_reminder_calculation_done_at",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
