# Generated by Django 5.1.4 on 2025-04-01 10:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_user_last_reminder_calculation_done_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="pending_clients",
            field=models.PositiveIntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
